image: python:alpine

before_script:
  - time pip install -r requirements.txt

pages:
  script:
  - time mkdocs build
  - time mv _site public
  artifacts:
    paths:
    - public
  only:
  - master

