# Replace the text below to customize your site
site_name: Fiore Basile - Fab Academy 2019
site_description: My Fabacademy site
site_url: http://fibasile.fabcloud.io/mkdocs
repo_url: https://gitlab.fabcloud.org/fibasile/mkdocs
site_author: Fiore Basile
docs_dir: docs 
site_dir: _site
copyright: Creative Commons Attribution Non Commercial
theme: 
    name: spacelab # try also cerulean, cosmo, cyborg, amelia, darkly, spacelab, united
    extra:
        include_sidebar: false
markdown_extensions:
    - toc:
        permalink: '#'
    - extra
    - smarty
